import logging
from pathlib import Path

from utils.ieee_802_11 import IeeeStandard


PROJECT_ROOT = Path(__file__).resolve().parents[1]
IEEE_802_11 = IeeeStandard().b_802_11

# Simulation
MAP_LENGTH = 600
MAP_WIDTH = 600
MAP_HEIGHT = 120
AIRSPACE_HEIGHT_ABOVE_TERRAIN = 120.0
SIM_TIME = 20 * 1e6
NUMBER_OF_DRONES = 10
UAV_SPEED = 10.0
UAV_MIN_ALTITUDE = None
UAV_MAX_ALTITUDE = None
TRAFFIC_PATTERN = "Poisson"
PACKET_ARRIVAL_RATE = 5.0
UAV_BUILDING_CLEARANCE = 1.0
UAV_BOUNDARY_CLEARANCE = 1.0
UAV_INITIAL_SEPARATION = 5.0
GRID_RESOLUTION = 20
STATIC_CASE = 0
HETEROGENEOUS = 0
LOGGING_LEVEL = logging.INFO
RANDOM_SEED = 2025

# Rotary-wing UAV
PROFILE_DRAG_COEFFICIENT = 0.012
AIR_DENSITY = 1.225
ROTOR_SOLIDITY = 0.05
ROTOR_DISC_AREA = 0.79
BLADE_ANGULAR_VELOCITY = 400
ROTOR_RADIUS = 0.5
INCREMENTAL_CORRECTION_FACTOR = 0.1
AIRCRAFT_WEIGHT = 100
ROTOR_BLADE_TIP_SPEED = 500
MEAN_ROTOR_VELOCITY = 7.2
FUSELAGE_DRAG_RATIO = 0.3
INITIAL_ENERGY = 20 * 1e3
ENERGY_THRESHOLD = 2000
MAX_QUEUE_SIZE = 200

# Radio and Sionna RT
TRANSMITTING_POWER = 0.1
CARRIER_FREQUENCY = IEEE_802_11["carrier_frequency"]
BANDWIDTH = IEEE_802_11["bandwidth"]
BIT_RATE = IEEE_802_11["bit_rate"]
BIT_TRANSMISSION_TIME = 1 / BIT_RATE * 1e6
THERMAL_NOISE_DENSITY_DBM_HZ = -174.0
RECEIVER_NOISE_FIGURE_DB = 7.0
SINR_THRESHOLD_DB = IEEE_802_11["snr_threshold"]
CCA_THRESHOLD_DBM = -82.0
SIONNA_SCENE_PATH = str(PROJECT_ROOT / "artifacts" / "scene" / "scene.xml")
SIONNA_MAX_DEPTH = 4
SIONNA_SAMPLES_PER_SOURCE = 100000
SIONNA_FREQUENCY_SAMPLES = 32
SIONNA_SEED = 2025
SIONNA_LOS = True
SIONNA_SPECULAR_REFLECTION = True
SIONNA_DIFFUSE_REFLECTION = False
SIONNA_REFRACTION = False
SIONNA_DIFFRACTION = False
SIONNA_EDGE_DIFFRACTION = False
CHANNEL_MODE = "online"
LOS_A2A_MODEL = "free_space"
NLOS_A2A_MODEL = "urban"
CALIBRATION_PROFILE = None
CHANNEL_SNAPSHOT_INTERVAL = 100000
CHANNEL_SNAPSHOT_DISPLACEMENT = 1.0
ROUTING_NEIGHBOR_DISTANCE = 300.0

# Packets
VARIABLE_PAYLOAD_LENGTH = 0
AVERAGE_PAYLOAD_LENGTH = 1024 * 8
MAXIMUM_PAYLOAD_VARIATION = 1600
MAX_TTL = NUMBER_OF_DRONES + 1
PACKET_LIFETIME = 10 * 1e6
IP_HEADER_LENGTH = 20 * 8
MAC_HEADER_LENGTH = 14 * 8
PLCP_PREAMBLE = 128 + 16
PLCP_HEADER = 8 + 8 + 16 + 16
PHY_HEADER_LENGTH = PLCP_PREAMBLE + PLCP_HEADER
ACK_HEADER_LENGTH = 16 * 8
ACK_PACKET_LENGTH = ACK_HEADER_LENGTH + 14 * 8
HELLO_PACKET_PAYLOAD_LENGTH = 256
HELLO_PACKET_LENGTH = IP_HEADER_LENGTH + MAC_HEADER_LENGTH + PHY_HEADER_LENGTH + HELLO_PACKET_PAYLOAD_LENGTH

GL_ID_DATA_PACKET = 0
GL_ID_HELLO_PACKET = 10000
GL_ID_ACK_PACKET = 20000
GL_ID_VF_PACKET = 30000
GL_ID_GRAD_MESSAGE = 40000

# MAC
SLOT_DURATION = IEEE_802_11["slot_duration"]
SIFS_DURATION = IEEE_802_11["SIFS"]
DIFS_DURATION = SIFS_DURATION + 2 * SLOT_DURATION
CW_MIN = 31
ACK_TIMEOUT = ACK_PACKET_LENGTH / BIT_RATE * 1e6 + SIFS_DURATION + 50
MAX_RETRANSMISSION_ATTEMPT = 5

# Protocol selection
ROUTING_PROTOCOL = "Greedy"
MAC_PROTOCOL = "CSMA_CA"
MOBILITY_MODEL = "GaussMarkov3D"
ROUTING_PROTOCOL_PARAMETERS = {}
DRL_ROUTING_PROTOCOL_CLASS = None
DRL_HELLO_PACKET_CLASS = None
DRL_NEIGHBOR_TABLE_CLASS = None


def reset_runtime_ids():
    global GL_ID_DATA_PACKET, GL_ID_HELLO_PACKET, GL_ID_ACK_PACKET, GL_ID_VF_PACKET, GL_ID_GRAD_MESSAGE
    GL_ID_DATA_PACKET = 0
    GL_ID_HELLO_PACKET = 10000
    GL_ID_ACK_PACKET = 20000
    GL_ID_VF_PACKET = 30000
    GL_ID_GRAD_MESSAGE = 40000


def noise_power_watt():
    noise_dbm = THERMAL_NOISE_DENSITY_DBM_HZ + 10 * __import__("math").log10(BANDWIDTH) + RECEIVER_NOISE_FIGURE_DB
    return 10 ** ((noise_dbm - 30) / 10)
